### ISSUE TITLE
Loading/Downloading Raw images error

### ISSUE THREAD

**Issue by Pamlau** [MapoMagpie/eh-view-enhance#76] opened 2024-07-25 22:46 UTC
Description: When loading/downloading any gallery with raw images, I get the error "[Error: expect image data, fetched wrong type: text/html; charset=utf-8]"

Browser: Opera GX version: LVL6 (core: 111.0.5168.99)

Log: Opera GX doesn't seem to have a log manager

![image](https://github.com/user-attachments/assets/84d510f2-a630-4894-9324-ccc6b2fcc74c)

![image](https://github.com/user-attachments/assets/4c10ccbd-e919-4f21-a619-e525c8df0f46)

**Comment by MapoMagpie** [comment] 2024-07-26 02:19
Fetch the raw image(original image), you need to be logged in. Please check if you are logged into e-hentai. 

I will make the error‘s description more accurate.

**Comment by Pamlau** [comment] 2024-07-26 12:33
> Fetch the raw image(original image), you need to be logged in. Please check if you are logged into e-hentai.
> 
> I will make the error‘s description more accurate.

I'm logged both on exhentai and e-hentai, both are giving the same error message, 1/10 of the images end up loading/downloading correctly but the rest give the same "[Error: expect image data, fetched wrong type]" message

**Comment by MapoMagpie** [comment] 2024-07-26 13:47
I can't reproduce this. 
Can You press the middle mouse button on the thumbnail to open the source address and click the `Download original xxx` button to see if you can download the image.

**Comment by Pamlau** [comment] 2024-07-26 13:55
> I can't reproduce this. Can You press the middle mouse button on the thumbnail to open the source address and click the `Download original xxx` button to see if you can download the image.

Yes, I'm able to download normally through the normal original button. I open the gallery, I press the button to open the gallery through the viewer, I press the download button and it starts attempting to download all images but 90% of them end up with the same error, I'll try with a different browser other than Opera GX

**Comment by MapoMagpie** [comment] 2024-07-28 15:42
I cannot reproduce the issue with error message `Error: expect image data, fetched wrong type: text/html; charset=utf-8`,
but there is indeed an issue with loading the source images. This is due to some nodes in the "hath.network" being down. 
I have now fixed the problem of not being able to get new "hath.network" nodes.
It might solve the issue you are encountering.

**Comment by Pamlau** [comment] 2024-07-28 19:39
> I cannot reproduce the issue with error message `Error: expect image data, fetched wrong type: text/html; charset=utf-8`, but there is indeed an issue with loading the source images. This is due to some nodes in the "hath.network" being down. I have now fixed the problem of not being able to get new "hath.network" nodes. It might solve the issue you are encountering.

![image](https://github.com/user-attachments/assets/07e53419-85ab-4dd9-a1d0-9a918b19784c)

![image](https://github.com/user-attachments/assets/06e3b685-cc71-4769-8f80-1235d76bbdc5)

**Comment by Pamlau** [comment] 2024-07-28 19:41
On google chrome its like that:

![image](https://github.com/user-attachments/assets/a6845434-5ff9-4f7c-bf7a-7589271a213c)

![image](https://github.com/user-attachments/assets/18ae036a-9154-47bc-bbcd-4605a65dce8d)

**Comment by MapoMagpie** [comment] 2024-07-29 00:35
Maybe the correct image data has been obtained, but strangely, the response data content-type is "text/html". 
I have tried to fix this.

**Comment by Pamlau** [comment] 2024-07-29 12:36
> Maybe the correct image data has been obtained, but strangely, the response data content-type is "text/html". I have tried to fix this.

The download is working now but its downloading a null file instead of the gallery

![image](https://github.com/user-attachments/assets/fa7396f6-9bb5-4514-a04f-21fc8c1da147)

![image](https://github.com/user-attachments/assets/d5e55c20-d210-4a3e-abcb-2175469aec8c)


All files are 173 KB and unable to open, tested other galleries too, some images actually end up being downloaded correctly in the original state, but most files in the null 173 KB state

**Comment by MapoMagpie** [comment] 2024-07-29 13:35
Could you upload one of the files? It seems that its data is not image data but HTML content.

**Comment by MapoMagpie** [comment] 2024-07-29 15:36
![grim_20240729_233009](https://github.com/user-attachments/assets/a966867a-158e-45cf-bb35-1e04500a3dc9)
Kaspersky blocked requests to "hath.network" from other browser extensions. 
"[hath.network](https://ehwiki.org/wiki/Hentai@Home)" is the content distribution network of "e-hentai."

**Comment by Pamlau** [comment] 2024-07-29 15:56
> hath.network

Kaspersky never blocked exhentai for me

I added the "hath.network" to Trusted URLs but still seems to not work, it keeps downloading 90% of the files as the 173 KB one

![image](https://github.com/user-attachments/assets/d75523f2-7742-4165-bf5f-ba761d9656fb)

The file: 
![01](https://github.com/user-attachments/assets/3395e25c-a9d1-4b1e-ae03-51baaadd1878)

**Comment by MapoMagpie** [comment] 2024-07-29 16:16
Try add this:"*.hath.network" to Trusted URLs

**Comment by Pamlau** [comment] 2024-07-29 16:46
> Try add this:"*.hath.network" to Trusted URLs

Now its downloading 28 KB files with or without anti-virus xdd

![image](https://github.com/user-attachments/assets/5b394e16-b142-48ac-a139-9c2f32f4418e)

![image](https://github.com/user-attachments/assets/49557c0c-443f-48a8-b79b-3f2abda80e63)

**Comment by Pamlau** [comment] 2024-07-29 17:36
UPDATE: Now all of sudden its working perfectly, with and without karpersky! Thanks you are the best <3

**Comment by MapoMagpie** [comment] 2024-07-29 17:39
Okey

**Closed** 2024-07-29 18:41 UTC
